//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framwork_project_Friendyol.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class fatura
    {
        public int faturaID { get; set; }
        public Nullable<int> musteriID { get; set; }
        public Nullable<int> siparisID { get; set; }
        public Nullable<int> firmaID { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<byte> is_flag { get; set; }
    }
}
