//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framwork_project_Friendyol.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma_Bilgisi
    {
        public int firmaID { get; set; }
        public string ad_soyad { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string e_mail { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<byte> is_flag { get; set; }
    }
}
