//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framwork_project_Friendyol.service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FRİENDYOLEntities : DbContext
    {
        public FRİENDYOLEntities()
            : base("name=FRİENDYOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fatura> fatura { get; set; }
        public virtual DbSet<marka> marka { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<view_marka> view_marka { get; set; }
        public virtual DbSet<wiew_fatura> wiew_fatura { get; set; }
        public virtual DbSet<siparis> siparis { get; set; }
        public virtual DbSet<view_siparis> view_siparis { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<urun> urun { get; set; }
        public virtual DbSet<view_kategori> view_kategori { get; set; }
        public virtual DbSet<view_urun> view_urun { get; set; }
        public virtual DbSet<kargo> kargo { get; set; }
        public virtual DbSet<view_kargo> view_kargo { get; set; }
        public virtual DbSet<yorumlar> yorumlar { get; set; }
        public virtual DbSet<view_yorumlar> view_yorumlar { get; set; }
        public virtual DbSet<firma_Bilgisi> firma_Bilgisi { get; set; }
        public virtual DbSet<view_firma_Bilgisi> view_firma_Bilgisi { get; set; }
        public virtual DbSet<musteri> musteri { get; set; }
        public virtual DbSet<view_musteri> view_musteri { get; set; }
    }
}
