//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framwork_project_Friendyol.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri
    {
        public int musteriID { get; set; }
        public string adSoyad { get; set; }
        public string ulke { get; set; }
        public string sehir { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string e_mail { get; set; }
        public Nullable<int> is_Admin { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<byte> is_flag { get; set; }
    }
}
