//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framwork_project_Friendyol.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public int urunID { get; set; }
        public Nullable<int> kategoriID { get; set; }
        public string urunAD { get; set; }
        public Nullable<int> markaID { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<int> stok { get; set; }
        public string acıklama { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<byte> is_flag { get; set; }
    }
}
