//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framwork_project_Friendyol.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_kargo
    {
        public int kargoID { get; set; }
        public string kargoAD { get; set; }
        public string kargoTEL { get; set; }
    }
}
